//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop20181019.Web.SysFun {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblNodeId;
	protected global::System.Web.UI.WebControls.Label lblDisplayName;
	protected global::System.Web.UI.WebControls.Label lblNodeURL;
	protected global::System.Web.UI.WebControls.Label lblDisplayOrder;
	protected global::System.Web.UI.WebControls.Label lblParentNodeId;


       
    }
}
