//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop20181019.Web.Books {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtAuthor;
		protected global::System.Web.UI.WebControls.TextBox txtPublisherId;
		protected global::System.Web.UI.WebControls.TextBox txtPublishDate;
	protected global::System.Web.UI.WebControls.Label lblISBN;
		protected global::System.Web.UI.WebControls.TextBox txtWordsCount;
		protected global::System.Web.UI.WebControls.TextBox txtUnitPrice;
		protected global::System.Web.UI.WebControls.TextBox txtContentDescription;
		protected global::System.Web.UI.WebControls.TextBox txtAurhorDescription;
		protected global::System.Web.UI.WebControls.TextBox txtEditorComment;
		protected global::System.Web.UI.WebControls.TextBox txtTOC;
		protected global::System.Web.UI.WebControls.TextBox txtCategoryId;
		protected global::System.Web.UI.WebControls.TextBox txtClicks;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
