//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop20181019.Web.Books {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblAuthor;
	protected global::System.Web.UI.WebControls.Label lblPublisherId;
	protected global::System.Web.UI.WebControls.Label lblPublishDate;
	protected global::System.Web.UI.WebControls.Label lblISBN;
	protected global::System.Web.UI.WebControls.Label lblWordsCount;
	protected global::System.Web.UI.WebControls.Label lblUnitPrice;
	protected global::System.Web.UI.WebControls.Label lblContentDescription;
	protected global::System.Web.UI.WebControls.Label lblAurhorDescription;
	protected global::System.Web.UI.WebControls.Label lblEditorComment;
	protected global::System.Web.UI.WebControls.Label lblTOC;
	protected global::System.Web.UI.WebControls.Label lblCategoryId;
	protected global::System.Web.UI.WebControls.Label lblClicks;


       
    }
}
