//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop20181019.Web.Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblLoginId;
	protected global::System.Web.UI.WebControls.Label lblLoginPwd;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblMail;
	protected global::System.Web.UI.WebControls.Label lblUserStateId;


       
    }
}
